export const countries = [
    { code: 'US', name: 'United States', emoji: '🇺🇸' },
    { code: 'GB', name: 'United Kingdom', emoji: '🇬🇧' },
    { code: 'CA', name: 'Canada', emoji: '🇨🇦' },
    { code: 'AU', name: 'Australia', emoji: '🇦🇺' },
    { code: 'DE', name: 'Germany', emoji: '🇩🇪' },
    { code: 'FR', name: 'France', emoji: '🇫🇷' },
    { code: 'ES', name: 'Spain', emoji: '🇪🇸' },
    { code: 'IT', name: 'Italy', emoji: '🇮🇹' },
    { code: 'JP', name: 'Japan', emoji: '🇯🇵' },
    { code: 'KR', name: 'South Korea', emoji: '🇰🇷' },
    { code: 'CN', name: 'China', emoji: '🇨🇳' },
    { code: 'IN', name: 'India', emoji: '🇮🇳' },
    { code: 'BR', name: 'Brazil', emoji: '🇧🇷' },
    { code: 'MX', name: 'Mexico', emoji: '🇲🇽' },
    { code: 'RU', name: 'Russia', emoji: '🇷🇺' },
    { code: 'UA', name: 'Ukraine', emoji: '🇺🇦' },
    { code: 'TR', name: 'Turkey', emoji: '🇹🇷' },
    { code: 'SA', name: 'Saudi Arabia', emoji: '🇸🇦' },
    { code: 'AE', name: 'United Arab Emirates', emoji: '🇦🇪' },
    { code: 'ZA', name: 'South Africa', emoji: '🇿🇦' },
    { code: 'NG', name: 'Nigeria', emoji: '🇳🇬' },
    { code: 'EG', name: 'Egypt', emoji: '🇪🇬' },
    { code: 'AR', name: 'Argentina', emoji: '🇦🇷' },
    { code: 'CO', name: 'Colombia', emoji: '🇨🇴' },
    { code: 'PL', name: 'Poland', emoji: '🇵🇱' },
    { code: 'NL', name: 'Netherlands', emoji: '🇳🇱' },
    { code: 'SE', name: 'Sweden', emoji: '🇸🇪' },
    { code: 'NO', name: 'Norway', emoji: '🇳🇴' },
    { code: 'DK', name: 'Denmark', emoji: '🇩🇰' },
    { code: 'FI', name: 'Finland', emoji: '🇫🇮' },
    { code: 'GE', name: 'Georgia', emoji: '🇬🇪' },
    { code: 'OTHER', name: 'Other', emoji: '🌍' }
].sort((a, b) => a.name.localeCompare(b.name));
